### ISSUE TITLE
Invalid Login, Credentials

### ISSUE THREAD

**Issue by def-mycroft** [tastyware/tastytrade-cli#1]
Hello @Graeme22 , 

When I first create an environment and attempt to run a command (e.g. `twcli option chain --strikes 3 SPY`), I get the below error: 

```
Exception: Failed to log in, message: Invalid login, please check your username and password. Unique customer support identifier: b5aecbb2a86c5416ff1974b27fe3963b
```

...I've been able to temporarily hard code the credentials and make it work, but what is the best way to setup credentials? 

It would be nice to update the README to include instructions for this, more accessible for new users.

**Comment by def-mycroft** [comment]
ah, actually, I see that it is in the config file now, I'll see if I can get that to work and might submit a PR for the README

**Comment by def-mycroft** [comment]
hmm, I added my creds to `/home/dasenbrj/.config/twcli/twcli.cfg` and now I get 

```
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.tastyworks.com', port=443): Max retries exceeded with url: /sessions/validate (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa2366f2950>, 'Connection to api.tastyworks.com timed out. (connect timeout=None)'))
```

**Comment by def-mycroft** [comment]
okay, I deleted `/home/dasenbrj/.config/twcli/.session`, must have been an old session or something, that got the command `twcli option chain --strikes 3 SPY` to work.

**Comment by Graeme22** [comment]
> ah, actually, I see that it is in the config file now, I'll see if I can get that to work and might submit a PR for the README

That would be great!

**Comment by def-mycroft** [comment]
I ended up figuring this out, so I'll close the issue (problem was related to a prior session token).
