### ISSUE TITLE
Provide Alternative to Plain-Text Password Storage in Config

### ISSUE THREAD

**Issue by def-mycroft** [tastyware/tastytrade-cli#2]
Hi @Graeme22 , what are your thoughts about storing login creds in a plain-text config file? 

I don't think it is a huge security problem, but there is (imo) a case to be made for it being sub-optimal. 

How feasible would it be to engineer a method that receives credentials from the user and maintains access for a period of time (e.g. 5 hours)?

**Comment by Graeme22** [comment]
Closing as this already exists. Would welcome documentation though!

**Comment by def-mycroft** [comment]
there is a way to store login credentials without storing them in a plain-text config file? 

just wanted to double check, the way I wrote the headline could have been misunderstood; I want to *not* store credentials in config file.

**Comment by def-mycroft** [comment]
changed the name of this issue to "Provide Alternative to Plain-Text Password Storage in Config".

**Comment by Graeme22** [comment]
> there is a way to store login credentials without storing them in a plain-text config file? 

Yes, there are two other options: enter the password on the command line; or export it to the `$TW_PASS` environment variable. Regardless of what method is used, the token will be cached and used for future logins and is valid for 24 hours from the first attempt.
